In [8]:
import scipy as sc
import numpy as np

## Integral 1
Integrate $\int_0^\infty r^k e^{-Br^2 -r} dr$

### Test 1

In [135]:
#x = np.linspace(-0.1, -10, 5)
pi = np.pi

#sc.special.hyperu(1, 1, x)

def G(k,x):
    return (pi)**(1/2)*sc.special.factorial(k)*np.exp(x)*x**(k/2+1)*\
    ((sc.special.hyperu(-k/2,1/2,-x))/(x**(1/2)*sc.special.gamma(k/2+1)) -\
     2*(sc.special.hyperu(-k/2,1/2,-x))/(sc.special.gamma((k+1)/2)))

In [137]:
#x = np.linspace(-10,-1,10)
#k=4

k=4
B = 0.8
G(k,1/(4*B))

nan

In [45]:
def G(k,x):
    return (pi)**(1/2)*sc.special.factorial(k)*np.exp(x)*x**(k/2+1)#*\
    #((sc.special.hyperu(-k/2,1/2,-x)))

x = np.linspace(10, 100, 10)
k=2
G(k,x)

array([7.80817882e+06, 6.87946335e+11, 3.40943094e+16, 1.33507047e+21,
       4.59482564e+25, 1.45739189e+30, 4.36932898e+34, 1.25702368e+39,
       3.50423580e+43, 9.52912716e+47])

In [39]:
sc.special.hyperu(-k/2,1/2,-x)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

### Test 2
Kummer's function, not hyperu!

In [75]:
#x = np.linspace(-0.1, -10, 5)
pi = np.pi

#sc.special.hyperu(1, 1, x)

def G(k,x):
    return (pi)**(1/2)*sc.special.factorial(k)*np.exp(x)*x**(k/2+1)*\
    ((sc.special.hyp1f1(-k/2,1/2,-x))/(x**(1/2)*sc.special.gamma(k/2+1)) -\
     2*(sc.special.hyp1f1((1-k)/2,3/2,-x))/(sc.special.gamma((k+1)/2)))

#x = np.linspace(-10,-1,10)
#k=4

k=4
B = 4
G(k,1/(4*B))

0.010074602839286835

In [76]:
sc.integrate.quad(lambda r: r**k*np.exp(-B*r**2-r), 0, np.inf)

(0.010074602839293744, 1.3767146378968278e-10)

## Integral 2
$\int_0^\infty r^k e^{-Ar^2} dr$

In [127]:
gam = lambda k,A: sc.special.gamma((k+1)/2)/(2*A**((k+1)/2))

## Solve matrix equations using analytical expression

In [96]:
#Solve
def GTO_1(a,b): 
    return lambda r: b*(2*a/pi)**(3/4)*np.exp(-a*r**2)
def STO_1():
    return lambda r: (1/pi)**(1/2)*np.exp(-r)
    
#B = np.array()
#W = np.array()
#P = np.array()

In [110]:
#Solve

def GTO_1(r):
    return b*(2*a/pi)**(3/4)*np.exp(-a*r**2)

def STO_1(r):
    return (1/pi)**(1/2)*np.exp(-r)
    
#B = np.array()
#W = np.array()
#P = np.array()

In [89]:
a = 1
GTO_1(a)

<function __main__.GTO_1.<locals>.<lambda>(r)>

In [115]:
a = 1
b = 1
    
sc.integrate.quad(lambda r: ((1/pi)**(1/2)*np.exp(-r) - b*(2*a/pi)**(3/4)*np.exp(-a*r**2))*( b*(2*a/pi)**(3/4)*np.exp(-a*r**2)), 0, np.inf)

(-0.09890694800826817, 9.817147292262516e-12)

In [145]:
#Solve
GTO_1 = lambda r: (2*a/pi)**(3/4)*np.exp(-a*r**2)
STO_1 = lambda r: pi**(-1/2)*np.exp(-r)

a = 1
b = 1
    
sc.integrate.quad(lambda r: (STO_1(r) - b*GTO_1(r))*GTO_1(r), 0, np.inf)

(-0.09890694800826817, 9.817147292262516e-12)

In [147]:
a = 1
b = 1

coef_GTO_1 = lambda a: (2*a/pi)**(3/4)
coef_STO_1 = pi**(-1/2)

gam = lambda k,A: sc.special.gamma((k+1)/2)/(2*A**((k+1)/2))

G = lambda k,x: (pi)**(1/2)*sc.special.factorial(k)*np.exp(x)*x**(k/2+1)*\
    ((sc.special.hyp1f1(-k/2,1/2,-x))/(x**(1/2)*sc.special.gamma(k/2+1)) -\
     2*(sc.special.hyp1f1((1-k)/2,3/2,-x))/(sc.special.gamma((k+1)/2)))

#remember the 1/(4*a)
coef_STO_1*coef_GTO_1(a)*G(0,1/(4*a)) - b*coef_GTO_1(a)**2*gam(0,2*a)

-0.09890694800826821

In [156]:
sc.integrate.quad(lambda r: (STO_1(r) - b*GTO_1(r))*GTO_1(r)*(3/(4*a) - r**2), 0, np.inf)

(-0.05862969246395515, 2.275796467612097e-09)

In [157]:
b*((coef_STO_1*coef_GTO_1(a)*G(0,1/(4*a)) - b*coef_GTO_1(a)**2*gam(0,2*a))*3/(4*a) - coef_GTO_1(a)\
*coef_STO_1*G(2,1/(4*a)) + b*coef_GTO_1(a)**2*gam(2,2*a))   

-0.058629692463947905

## Solve matrix equations using matrix, integrate using quad

### using exec()

First, determine how many GTOs to use.
Then use exec?

In [ ]:
GTO_1 = lambda r,a: (2*a/pi)**(3/4)*np.exp(-a*r**2)
STO_1 = lambda r: pi**(-1/2)*np.exp(-r)
#sc.integrate.quad(lamdbda r:(STO_1(r) - GTO_1(r))*(GTO_1(r)) ,0, np.inf)

In [166]:
main = '''
a
'''

print(main + 'b \n' + 'c')


a
b 
c


In [ ]:
main 
#1

#2

#3





In [192]:
num_GTO = int(input('how many GTOs?'))

#add GTOs to chi
str_chi = 'chi = lambda r: d1*GTO_1(r,a1)'

for i in range(2, num_GTO +1):
    str_chi += '+ d{0}*GTO_1(r,a{0}) '.format(i)
    
str_chi += '\n'

#add the a's
str_a_s = 'a1 = P[0] \n'

for i in range(2, num_GTO +1):
    str_a_s += 'a{0} = P[{1}] \n'.format(i,i-1)

str_d_s = 'd1 = P[{0}] \n'.format(num_GTO)

for i in range(2, num_GTO +1):
    str_d_s += 'd{0} = P[{1}] \n'.format(i,num_GTO+i-1)

print(str_a_s)
print(str_d_s)

# initial value of P
P = np.array()

how many GTOs? 2


a1 = P[0] 
a2 = P[1] 

d1 = P[2] 
d2 = P[3] 



In [171]:
+1

1

In [175]:
str_b_integral = 'sp.integrate.quad(lamdbda r:(STO_1(r) - chi(r))*(par_chi_i(r)) ,0, np.inf)'
list_B = [exec() for i in range(1,2*num_GTO + 1)]

In [199]:
list_B = [exec('sc.integrate.quad(lambda x: x**{0},0,1)'.format(i)) for i in range(1,2*num_GTO + 1)]
list_B

[None, None, None, None]

In [200]:
def return_int(i):
    return sc.integrate.quad(lambda x: x**i,0,1)
list_B = [exec('return_int({0})'.format(i)) for i in range(1,2*num_GTO + 1)]
list_B

[None, None, None, None]

In [201]:
return_int(1)

(0.5, 5.551115123125783e-15)

### using list and exec

In [286]:
num_GTO = int(input('how many GTOs?'))

#add GTOs to chi
str_chi = 'd[0]*GTO_1(r,a[0])'

for i in range(2, num_GTO +1):
    str_chi += '+ d[{0}]*GTO_1(r,a[{0}]) '.format(i-1)
    
str_chi += '\n'

# initial value of P
#P = np.zeros(2*num_GTO + 1) + 0.1
P = [i*0.05 for i in range (1,2*num_GTO + 2)]

#a array
a = P[0 : num_GTO]
#d list
d = P[num_GTO : 2*num_GTO+1]

lambd = P[2*num_GTO]

how many GTOs? 2


In [287]:
GTO_1 = lambda r,a: (2*a/pi)**(3/4)*np.exp(-a*r**2)
STO_1 = lambda r: pi**(-1/2)*np.exp(-r)
par_GTO_a = lambda r,i: (GTO_1(r,a[i-1]))
par_GTO_d = lambda r,i: (GTO_1(r,a[i-1]))*(3/(4*a[i-1] - r**2))

def integ(x):
    return sc.integrate.quad(x ,0, np.inf)[0]

main = '''
b_integral_a = lambda i: integ(lambda r:(STO_1(r) - {0})*par_GTO_a(r,i))

b_integral_d = lambda i:integ(lambda r:(STO_1(r) - {0})*par_GTO_d(r,i))

list_B = [b_integral_a(i) for i in range(1,num_GTO + 1)] + \
[b_integral_d(i) for i in range(1, num_GTO + 1)]

array_B = np.array(list_B)
'''.format(str_chi)

exec(main)

<ipython-input-287-e77bd4d3102f>:7: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return sc.integrate.quad(x ,0, np.inf)[0]
<ipython-input-287-e77bd4d3102f>:7: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  return sc.integrate.quad(x ,0, np.inf)[0]


In [255]:
print(list_B)
print(array_B)

[0.061879718067350827, 0.061879718067350827, 0.6532912487988252, 0.6532912487988252]
[0.06187972 0.06187972 0.65329125 0.65329125]


Why is it truncated?

In [288]:
#Partition into four blocks, up_left, up_right = low_left transpose, up_right
#j is row, k is colume
up_left = [[ integ(lambda r: par_GTO_a(r,j)*par_GTO_a(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]

up_right = [[ integ(lambda r: par_GTO_a(r,j)*par_GTO_d(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]

low_left= [[ integ(lambda r: par_GTO_d(r,j)*par_GTO_a(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]
            
low_right = [[ integ(lambda r: par_GTO_d(r,j)*par_GTO_d(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]

#Add same column
array_W = np.array([up_left[i] + low_left[i] for i in range(0, num_GTO)] + [up_right[i] + low_right[i] for i in range(0, num_GTO)])
P += np.linalg.solve(array_W, array_B)

<ipython-input-287-e77bd4d3102f>:7: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return sc.integrate.quad(x ,0, np.inf)[0]
<ipython-input-287-e77bd4d3102f>:7: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  return sc.integrate.quad(x ,0, np.inf)[0]
<ipython-input-287-e77bd4d3102f>:7: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  re

In [289]:
array_W

array([[ 1.59154943e-02,  2.18548082e-02,  1.53933000e-02,
         2.92215456e-02],
       [ 2.18548082e-02,  3.18309886e-02, -2.50367572e-02,
        -3.62074663e-02],
       [ 1.53933000e-02, -2.50367572e-02,  6.42544758e+06,
        -1.57042653e+01],
       [ 2.92215456e-02, -3.62074663e-02, -1.57042653e+01,
         1.64188454e+01]])

In [290]:
np.linalg.solve(array_W, array_B)

array([-8.13504311e+00,  7.70913802e+00,  2.58670713e-07,  7.26915493e-02])

In [345]:
num_GTO = int(input('how many GTOs?'))

#add GTOs to chi
str_chi = 'd[0]*GTO_1(r,a[0])'

for i in range(2, num_GTO +1):
    str_chi += '+ d[{0}]*GTO_1(r,a[{0}]) '.format(i-1)
    
str_chi += '\n'

# initial value of P
#P = np.zeros(2*num_GTO + 1) + 0.1
P = [i*0.05 for i in range (1,2*num_GTO + 2)]

#a array
a = P[0 : num_GTO]
#d list
d = P[num_GTO : 2*num_GTO+1]

lambd = P[2*num_GTO]

how many GTOs? 2


In [344]:
GTO_1 = lambda r,a: (2*a/pi)**(3/4)*np.exp(-a*r**2)
STO_1 = lambda r: pi**(-1/2)*np.exp(-r)
par_GTO_a = lambda r,i: (GTO_1(r,a[i-1]))
par_GTO_d = lambda r,i: (GTO_1(r,a[i-1]))*(3/(4*a[i-1] - r**2))

def integ(x):
    return sc.integrate.quad(x ,0, np.inf)[0]

main = '''
b_integral_a = lambda i: integ(lambda r:(STO_1(r) - {0})*par_GTO_a(r,i))

b_integral_d = lambda i:integ(lambda r:(STO_1(r) - {0})*par_GTO_d(r,i))

list_B = [b_integral_a(i) for i in range(1,num_GTO + 1)] + \
[b_integral_d(i) for i in range(1, num_GTO + 1)] +\
[0.5*(1 - integ(lambda r: ({0}**2 )))]

array_B = np.array(list_B)

#for our lagrange multiplier
last_row = [integ(lambda r: {0}*b_integral_a(i))for k in range (1,num_GTO+1)] +\
[integ(lambda r: {0}*b_integral_d(i))for k in range (1,num_GTO+1)] + [0]

#last colum is constant
lambd_const = 1 - integ(lambda r: {0}**2)
'''.format(str_chi)

exec(main)

#Partition into four blocks, up_left, up_right = low_left transpose, up_right
#j is row, k is column
up_left = [[ integ(lambda r: par_GTO_a(r,j)*par_GTO_a(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]

up_right = [[ integ(lambda r: par_GTO_a(r,j)*par_GTO_d(r,k)) for k in range (1,num_GTO+1)] + [1] for j in range (1,num_GTO+1)]

low_left= [[ integ(lambda r: par_GTO_d(r,j)*par_GTO_a(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]
            
low_right = [[ integ(lambda r: par_GTO_d(r,j)*par_GTO_d(r,k)) for k in range (1,num_GTO+1)] + [1] for j in range (1,num_GTO+1)]

#Add same rows
list_W = [up_left[i] + up_right[i] for i in range(0, num_GTO)] + [low_left[i] + low_right[i] for i in range(0, num_GTO)] + [last_row]
array_W = np.array(list_W)

solution = np.linalg.solve(array_W, array_B)
P += solution

print(P)

<ipython-input-344-12f31499e076>:7: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return sc.integrate.quad(x ,0, np.inf)[0]
<ipython-input-344-12f31499e076>:7: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  return sc.integrate.quad(x ,0, np.inf)[0]


[ 34.89036613 -15.74273516   0.15000033   0.30812452   0.1267107 ]


<ipython-input-344-12f31499e076>:7: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  return sc.integrate.quad(x ,0, np.inf)[0]


In [343]:
print(P)

[17.47018306 -7.82136758  0.15000017  0.25406226  0.18835535]


## need to add lambda

In [327]:
up_left = [[integ(lambda r: par_GTO_a(r,j)*par_GTO_a(r,k)) for k in range (1,num_GTO+1)]  + [1] for j in range (1,num_GTO+1)]

Added lambda, fixed integral, P cannot be all same otherwise singular matrix

In [351]:
num_GTO = int(input('how many GTOs?'))

#add GTOs to chi
str_chi = 'd[0]*GTO_1(r,a[0])'

for i in range(2, num_GTO +1):
    str_chi += '+ d[{0}]*GTO_1(r,a[{0}]) '.format(i-1)
    
str_chi += '\n'

# initial value of P
P = np.zeros(2*num_GTO + 1) + 0.1
#P = [i*0.05 for i in range (1,2*num_GTO + 2)]

#a array
a = P[0 : num_GTO]
#d list
d = P[num_GTO : 2*num_GTO+1]

lambd = P[2*num_GTO]

how many GTOs? 2


In [352]:
GTO_1 = lambda r,a: (2*a/pi)**(3/4)*np.exp(-a*r**2)
STO_1 = lambda r: pi**(-1/2)*np.exp(-r)
par_GTO_a = lambda r,i: (GTO_1(r,a[i-1]))
par_GTO_d = lambda r,i: (GTO_1(r,a[i-1]))*(3/(4*a[i-1] - r**2))

def integ(x):
    return sc.integrate.quad(lambda r: x(r)*r**2 ,0, np.inf)[0]

main = '''
b_integral_a = lambda i: integ(lambda r:(STO_1(r) - {0})*par_GTO_a(r,i))

b_integral_d = lambda i:integ(lambda r:(STO_1(r) - {0})*par_GTO_d(r,i))

list_B = [b_integral_a(i) for i in range(1,num_GTO + 1)] + \
[b_integral_d(i) for i in range(1, num_GTO + 1)] +\
[0.5*(1 - integ(lambda r: ({0}**2 )))]

array_B = np.array(list_B)

#for our lagrange multiplier
last_row = [integ(lambda r: {0}*b_integral_a(i))for k in range (1,num_GTO+1)] +\
[integ(lambda r: {0}*b_integral_d(i))for k in range (1,num_GTO+1)] + [0]

#last colum is constant
lambd_const = 1 - integ(lambda r: {0}**2)
'''.format(str_chi)

exec(main)

#Partition into four blocks, up_left, up_right = low_left transpose, up_right
#j is row, k is column
up_left = [[ integ(lambda r: par_GTO_a(r,j)*par_GTO_a(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]

up_right = [[ integ(lambda r: par_GTO_a(r,j)*par_GTO_d(r,k)) for k in range (1,num_GTO+1)] + [1] for j in range (1,num_GTO+1)]

low_left= [[ integ(lambda r: par_GTO_d(r,j)*par_GTO_a(r,k)) for k in range (1,num_GTO+1)] for j in range (1,num_GTO+1)]
            
low_right = [[ integ(lambda r: par_GTO_d(r,j)*par_GTO_d(r,k)) for k in range (1,num_GTO+1)] + [1] for j in range (1,num_GTO+1)]

#Add same rows
list_W = [up_left[i] + up_right[i] for i in range(0, num_GTO)] + [low_left[i] + low_right[i] for i in range(0, num_GTO)] + [last_row]
array_W = np.array(list_W)

solution = np.linalg.solve(array_W, array_B)
P += solution

print(P)

<ipython-input-352-094cdf5cfd20>:7: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return sc.integrate.quad(lambda r: x(r)*r**2 ,0, np.inf)[0]


LinAlgError: Singular matrix

In [349]:
print(P)

[-1.74695737  3.05387369  0.14999983  0.16740512  0.28978033]
